---
version: '3'
services:
  umami:
    container_name: umami
    # Original image does not support ARM
    # image: ghcr.io/mikecao/umami:postgresql-latest
    build: .
    ports:
      - "8333:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-stringggggg-right-nowww
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data:
